name: turtle-test

on:
  push:
  schedule:
    - cron: '0 */8 * * *'

jobs: 
  turtle-docker-image-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker login
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: treehouses turtleblocksjs
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="jleekwong/turtleblocksjs"
          source .github/workflows/utils.sh
          turtle_arm_sha=$(get_manifest_sha "$repo:latest" "arm")
          echo $turtle_arm_sha
          nginx_arm_sha=$(get_manifest_sha "treehouses/nginx:latest" "arm")
          echo $nginx_arm_sha
          flag_arm=$(is_base "treehouses/nginx@"$nginx_arm_sha "$repo@"$turtle_arm_sha)
          echo $flag_arm
          turtle_amd64_sha=$(get_manifest_sha "$repo:latest" "amd64")
          echo $turtle_amd64_sha
          nginx_amd64_sha=$(get_manifest_sha "treehouses/nginx:latest" "amd64")
          echo $nginx_amd64_sha
          flag_amd64=$(is_base "treehouses/nginx@"$nginx_amd64_sha "$repo@"$turtle_amd64_sha)
          echo $flag_amd64
          turtle_arm64_sha=$(get_manifest_sha "$repo:latest" "arm64")
          echo $turtle_arm64_sha
          nginx_arm64_sha=$(get_manifest_sha "treehouses/nginx:latest" "arm64")
          echo $nginx_arm64_sha
          flag_arm64=$(is_base "treehouses/nginx@"$nginx_arm64_sha "$repo@"$turtle_arm64_sha)
          echo $flag_arm64
          flag=$(compare "treehouses/nginx@"$nginx_arm_sha "$repo@"$turtle_arm_sha "treehouses/nginx@"$nginx_amd64_sha "$repo@"$turtle_amd64_sha "treehouses/nginx@"$nginx_arm64_sha "$repo@"$turtle_arm64_sha)
          echo $flag
          deploy_image "$repo" arm
          deploy_image "$repo" amd64
          deploy_image "$repo" arm64
          tag=$(date +%Y%m%d%H%M)
          tag2="latest"
          echo $tag
          create_manifest $repo $tag $tag2 $repo-tags:amd64 $repo-tags:arm $repo-tags:arm64
          docker manifest inspect $repo:$tag
          docker manifest inspect $repo:$tag2
          if [[ $flag == true ]]; then
            docker manifest push $repo:$tag; docker manifest push $repo:$tag2
          else
            echo "no changes"
          fi
